/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDesignBriefRouteImport } from './routes/web-design-brief'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SocialMediaBriefRouteImport } from './routes/social-media-brief'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeoBriefRouteImport } from './routes/seo-brief'
import { Route as RentWebsiteBriefRouteImport } from './routes/rent-website-brief'
import { Route as PayPerLeadServiceBriefRouteImport } from './routes/pay-per-lead-service-brief'
import { Route as PayPerLeadForTradiesRouteImport } from './routes/pay-per-lead-for-tradies'
import { Route as LocationRouteImport } from './routes/location'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GrowYourBusinessFormRouteImport } from './routes/grow-your-business-form'
import { Route as GoogleAdsBriefRouteImport } from './routes/google-ads-brief'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as LocationIndexRouteImport } from './routes/location.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesWebDesignRouteImport } from './routes/services.web-design'
import { Route as ServicesSocialMediaMarketingRouteImport } from './routes/services.social-media-marketing'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesRentWebsiteRouteImport } from './routes/services.rent-website'
import { Route as ServicesPayPerLeadRouteImport } from './routes/services.pay-per-lead'
import { Route as ServicesGoogleAdsRouteImport } from './routes/services.google-ads'
import { Route as LocationSlugRouteImport } from './routes/location.$slug'
import { Route as IndustriesDigitalMarketingForTradieRouteImport } from './routes/industries.digital-marketing-for-tradie'
import { Route as IndustriesDigitalMarketingForSmallBusinessesRouteImport } from './routes/industries.digital-marketing-for-small-businesses'
import { Route as IndustriesDigitalMarketingForRestaurantRouteImport } from './routes/industries.digital-marketing-for-restaurant'
import { Route as IndustriesDigitalMarketingForRealEstatesRouteImport } from './routes/industries.digital-marketing-for-real-estates'
import { Route as IndustriesDigitalMarketingForProfessionalServicesRouteImport } from './routes/industries.digital-marketing-for-professional-services'
import { Route as IndustriesDigitalMarketingForNonProfitsRouteImport } from './routes/industries.digital-marketing-for-non-profits'
import { Route as IndustriesDigitalMarketingForLawFirmsRouteImport } from './routes/industries.digital-marketing-for-law-firms'
import { Route as IndustriesDigitalMarketingForFitnessRouteImport } from './routes/industries.digital-marketing-for-fitness'
import { Route as IndustriesDigitalMarketingForFinancialServicesRouteImport } from './routes/industries.digital-marketing-for-financial-services'
import { Route as IndustriesDigitalMarketingForDoctorRouteImport } from './routes/industries.digital-marketing-for-doctor'
import { Route as IndustriesDigitalMarketingForDentistsRouteImport } from './routes/industries.digital-marketing-for-dentists'
import { Route as IndustriesDigitalMarketingForBeautySkincareRouteImport } from './routes/industries.digital-marketing-for-beauty-skincare'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'

const WebDesignBriefRoute = WebDesignBriefRouteImport.update({
  id: '/web-design-brief',
  path: '/web-design-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaBriefRoute = SocialMediaBriefRouteImport.update({
  id: '/social-media-brief',
  path: '/social-media-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoBriefRoute = SeoBriefRouteImport.update({
  id: '/seo-brief',
  path: '/seo-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const RentWebsiteBriefRoute = RentWebsiteBriefRouteImport.update({
  id: '/rent-website-brief',
  path: '/rent-website-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const PayPerLeadServiceBriefRoute = PayPerLeadServiceBriefRouteImport.update({
  id: '/pay-per-lead-service-brief',
  path: '/pay-per-lead-service-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const PayPerLeadForTradiesRoute = PayPerLeadForTradiesRouteImport.update({
  id: '/pay-per-lead-for-tradies',
  path: '/pay-per-lead-for-tradies',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowYourBusinessFormRoute = GrowYourBusinessFormRouteImport.update({
  id: '/grow-your-business-form',
  path: '/grow-your-business-form',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleAdsBriefRoute = GoogleAdsBriefRouteImport.update({
  id: '/google-ads-brief',
  path: '/google-ads-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesWebDesignRoute = ServicesWebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSocialMediaMarketingRoute =
  ServicesSocialMediaMarketingRouteImport.update({
    id: '/social-media-marketing',
    path: '/social-media-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRentWebsiteRoute = ServicesRentWebsiteRouteImport.update({
  id: '/rent-website',
  path: '/rent-website',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPayPerLeadRoute = ServicesPayPerLeadRouteImport.update({
  id: '/pay-per-lead',
  path: '/pay-per-lead',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGoogleAdsRoute = ServicesGoogleAdsRouteImport.update({
  id: '/google-ads',
  path: '/google-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationRoute,
} as any)
const IndustriesDigitalMarketingForTradieRoute =
  IndustriesDigitalMarketingForTradieRouteImport.update({
    id: '/digital-marketing-for-tradie',
    path: '/digital-marketing-for-tradie',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForSmallBusinessesRoute =
  IndustriesDigitalMarketingForSmallBusinessesRouteImport.update({
    id: '/digital-marketing-for-small-businesses',
    path: '/digital-marketing-for-small-businesses',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForRestaurantRoute =
  IndustriesDigitalMarketingForRestaurantRouteImport.update({
    id: '/digital-marketing-for-restaurant',
    path: '/digital-marketing-for-restaurant',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForRealEstatesRoute =
  IndustriesDigitalMarketingForRealEstatesRouteImport.update({
    id: '/digital-marketing-for-real-estates',
    path: '/digital-marketing-for-real-estates',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForProfessionalServicesRoute =
  IndustriesDigitalMarketingForProfessionalServicesRouteImport.update({
    id: '/digital-marketing-for-professional-services',
    path: '/digital-marketing-for-professional-services',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForNonProfitsRoute =
  IndustriesDigitalMarketingForNonProfitsRouteImport.update({
    id: '/digital-marketing-for-non-profits',
    path: '/digital-marketing-for-non-profits',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForLawFirmsRoute =
  IndustriesDigitalMarketingForLawFirmsRouteImport.update({
    id: '/digital-marketing-for-law-firms',
    path: '/digital-marketing-for-law-firms',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForFitnessRoute =
  IndustriesDigitalMarketingForFitnessRouteImport.update({
    id: '/digital-marketing-for-fitness',
    path: '/digital-marketing-for-fitness',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForFinancialServicesRoute =
  IndustriesDigitalMarketingForFinancialServicesRouteImport.update({
    id: '/digital-marketing-for-financial-services',
    path: '/digital-marketing-for-financial-services',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForDoctorRoute =
  IndustriesDigitalMarketingForDoctorRouteImport.update({
    id: '/digital-marketing-for-doctor',
    path: '/digital-marketing-for-doctor',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForDentistsRoute =
  IndustriesDigitalMarketingForDentistsRouteImport.update({
    id: '/digital-marketing-for-dentists',
    path: '/digital-marketing-for-dentists',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesDigitalMarketingForBeautySkincareRoute =
  IndustriesDigitalMarketingForBeautySkincareRouteImport.update({
    id: '/digital-marketing-for-beauty-skincare',
    path: '/digital-marketing-for-beauty-skincare',
    getParentRoute: () => IndustriesRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/google-ads-brief': typeof GoogleAdsBriefRoute
  '/grow-your-business-form': typeof GrowYourBusinessFormRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/location': typeof LocationRouteWithChildren
  '/pay-per-lead-for-tradies': typeof PayPerLeadForTradiesRoute
  '/pay-per-lead-service-brief': typeof PayPerLeadServiceBriefRoute
  '/rent-website-brief': typeof RentWebsiteBriefRoute
  '/seo-brief': typeof SeoBriefRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-brief': typeof SocialMediaBriefRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design-brief': typeof WebDesignBriefRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/digital-marketing-for-beauty-skincare': typeof IndustriesDigitalMarketingForBeautySkincareRoute
  '/industries/digital-marketing-for-dentists': typeof IndustriesDigitalMarketingForDentistsRoute
  '/industries/digital-marketing-for-doctor': typeof IndustriesDigitalMarketingForDoctorRoute
  '/industries/digital-marketing-for-financial-services': typeof IndustriesDigitalMarketingForFinancialServicesRoute
  '/industries/digital-marketing-for-fitness': typeof IndustriesDigitalMarketingForFitnessRoute
  '/industries/digital-marketing-for-law-firms': typeof IndustriesDigitalMarketingForLawFirmsRoute
  '/industries/digital-marketing-for-non-profits': typeof IndustriesDigitalMarketingForNonProfitsRoute
  '/industries/digital-marketing-for-professional-services': typeof IndustriesDigitalMarketingForProfessionalServicesRoute
  '/industries/digital-marketing-for-real-estates': typeof IndustriesDigitalMarketingForRealEstatesRoute
  '/industries/digital-marketing-for-restaurant': typeof IndustriesDigitalMarketingForRestaurantRoute
  '/industries/digital-marketing-for-small-businesses': typeof IndustriesDigitalMarketingForSmallBusinessesRoute
  '/industries/digital-marketing-for-tradie': typeof IndustriesDigitalMarketingForTradieRoute
  '/location/$slug': typeof LocationSlugRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/pay-per-lead': typeof ServicesPayPerLeadRoute
  '/services/rent-website': typeof ServicesRentWebsiteRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/location/': typeof LocationIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/google-ads-brief': typeof GoogleAdsBriefRoute
  '/grow-your-business-form': typeof GrowYourBusinessFormRoute
  '/pay-per-lead-for-tradies': typeof PayPerLeadForTradiesRoute
  '/pay-per-lead-service-brief': typeof PayPerLeadServiceBriefRoute
  '/rent-website-brief': typeof RentWebsiteBriefRoute
  '/seo-brief': typeof SeoBriefRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-brief': typeof SocialMediaBriefRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design-brief': typeof WebDesignBriefRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/digital-marketing-for-beauty-skincare': typeof IndustriesDigitalMarketingForBeautySkincareRoute
  '/industries/digital-marketing-for-dentists': typeof IndustriesDigitalMarketingForDentistsRoute
  '/industries/digital-marketing-for-doctor': typeof IndustriesDigitalMarketingForDoctorRoute
  '/industries/digital-marketing-for-financial-services': typeof IndustriesDigitalMarketingForFinancialServicesRoute
  '/industries/digital-marketing-for-fitness': typeof IndustriesDigitalMarketingForFitnessRoute
  '/industries/digital-marketing-for-law-firms': typeof IndustriesDigitalMarketingForLawFirmsRoute
  '/industries/digital-marketing-for-non-profits': typeof IndustriesDigitalMarketingForNonProfitsRoute
  '/industries/digital-marketing-for-professional-services': typeof IndustriesDigitalMarketingForProfessionalServicesRoute
  '/industries/digital-marketing-for-real-estates': typeof IndustriesDigitalMarketingForRealEstatesRoute
  '/industries/digital-marketing-for-restaurant': typeof IndustriesDigitalMarketingForRestaurantRoute
  '/industries/digital-marketing-for-small-businesses': typeof IndustriesDigitalMarketingForSmallBusinessesRoute
  '/industries/digital-marketing-for-tradie': typeof IndustriesDigitalMarketingForTradieRoute
  '/location/$slug': typeof LocationSlugRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/pay-per-lead': typeof ServicesPayPerLeadRoute
  '/services/rent-website': typeof ServicesRentWebsiteRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/location': typeof LocationIndexRoute
  '/services': typeof ServicesIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/google-ads-brief': typeof GoogleAdsBriefRoute
  '/grow-your-business-form': typeof GrowYourBusinessFormRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/location': typeof LocationRouteWithChildren
  '/pay-per-lead-for-tradies': typeof PayPerLeadForTradiesRoute
  '/pay-per-lead-service-brief': typeof PayPerLeadServiceBriefRoute
  '/rent-website-brief': typeof RentWebsiteBriefRoute
  '/seo-brief': typeof SeoBriefRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-brief': typeof SocialMediaBriefRoute
  '/thank-you': typeof ThankYouRoute
  '/web-design-brief': typeof WebDesignBriefRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/digital-marketing-for-beauty-skincare': typeof IndustriesDigitalMarketingForBeautySkincareRoute
  '/industries/digital-marketing-for-dentists': typeof IndustriesDigitalMarketingForDentistsRoute
  '/industries/digital-marketing-for-doctor': typeof IndustriesDigitalMarketingForDoctorRoute
  '/industries/digital-marketing-for-financial-services': typeof IndustriesDigitalMarketingForFinancialServicesRoute
  '/industries/digital-marketing-for-fitness': typeof IndustriesDigitalMarketingForFitnessRoute
  '/industries/digital-marketing-for-law-firms': typeof IndustriesDigitalMarketingForLawFirmsRoute
  '/industries/digital-marketing-for-non-profits': typeof IndustriesDigitalMarketingForNonProfitsRoute
  '/industries/digital-marketing-for-professional-services': typeof IndustriesDigitalMarketingForProfessionalServicesRoute
  '/industries/digital-marketing-for-real-estates': typeof IndustriesDigitalMarketingForRealEstatesRoute
  '/industries/digital-marketing-for-restaurant': typeof IndustriesDigitalMarketingForRestaurantRoute
  '/industries/digital-marketing-for-small-businesses': typeof IndustriesDigitalMarketingForSmallBusinessesRoute
  '/industries/digital-marketing-for-tradie': typeof IndustriesDigitalMarketingForTradieRoute
  '/location/$slug': typeof LocationSlugRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/pay-per-lead': typeof ServicesPayPerLeadRoute
  '/services/rent-website': typeof ServicesRentWebsiteRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/location/': typeof LocationIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blog'
    | '/contact-us'
    | '/google-ads-brief'
    | '/grow-your-business-form'
    | '/industries'
    | '/location'
    | '/pay-per-lead-for-tradies'
    | '/pay-per-lead-service-brief'
    | '/rent-website-brief'
    | '/seo-brief'
    | '/services'
    | '/sitemap.xml'
    | '/social-media-brief'
    | '/thank-you'
    | '/web-design-brief'
    | '/blog/$slug'
    | '/industries/digital-marketing-for-beauty-skincare'
    | '/industries/digital-marketing-for-dentists'
    | '/industries/digital-marketing-for-doctor'
    | '/industries/digital-marketing-for-financial-services'
    | '/industries/digital-marketing-for-fitness'
    | '/industries/digital-marketing-for-law-firms'
    | '/industries/digital-marketing-for-non-profits'
    | '/industries/digital-marketing-for-professional-services'
    | '/industries/digital-marketing-for-real-estates'
    | '/industries/digital-marketing-for-restaurant'
    | '/industries/digital-marketing-for-small-businesses'
    | '/industries/digital-marketing-for-tradie'
    | '/location/$slug'
    | '/services/google-ads'
    | '/services/pay-per-lead'
    | '/services/rent-website'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/web-design'
    | '/blog/'
    | '/industries/'
    | '/location/'
    | '/services/'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/google-ads-brief'
    | '/grow-your-business-form'
    | '/pay-per-lead-for-tradies'
    | '/pay-per-lead-service-brief'
    | '/rent-website-brief'
    | '/seo-brief'
    | '/sitemap.xml'
    | '/social-media-brief'
    | '/thank-you'
    | '/web-design-brief'
    | '/blog/$slug'
    | '/industries/digital-marketing-for-beauty-skincare'
    | '/industries/digital-marketing-for-dentists'
    | '/industries/digital-marketing-for-doctor'
    | '/industries/digital-marketing-for-financial-services'
    | '/industries/digital-marketing-for-fitness'
    | '/industries/digital-marketing-for-law-firms'
    | '/industries/digital-marketing-for-non-profits'
    | '/industries/digital-marketing-for-professional-services'
    | '/industries/digital-marketing-for-real-estates'
    | '/industries/digital-marketing-for-restaurant'
    | '/industries/digital-marketing-for-small-businesses'
    | '/industries/digital-marketing-for-tradie'
    | '/location/$slug'
    | '/services/google-ads'
    | '/services/pay-per-lead'
    | '/services/rent-website'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/web-design'
    | '/blog'
    | '/industries'
    | '/location'
    | '/services'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/blog'
    | '/contact-us'
    | '/google-ads-brief'
    | '/grow-your-business-form'
    | '/industries'
    | '/location'
    | '/pay-per-lead-for-tradies'
    | '/pay-per-lead-service-brief'
    | '/rent-website-brief'
    | '/seo-brief'
    | '/services'
    | '/sitemap.xml'
    | '/social-media-brief'
    | '/thank-you'
    | '/web-design-brief'
    | '/blog/$slug'
    | '/industries/digital-marketing-for-beauty-skincare'
    | '/industries/digital-marketing-for-dentists'
    | '/industries/digital-marketing-for-doctor'
    | '/industries/digital-marketing-for-financial-services'
    | '/industries/digital-marketing-for-fitness'
    | '/industries/digital-marketing-for-law-firms'
    | '/industries/digital-marketing-for-non-profits'
    | '/industries/digital-marketing-for-professional-services'
    | '/industries/digital-marketing-for-real-estates'
    | '/industries/digital-marketing-for-restaurant'
    | '/industries/digital-marketing-for-small-businesses'
    | '/industries/digital-marketing-for-tradie'
    | '/location/$slug'
    | '/services/google-ads'
    | '/services/pay-per-lead'
    | '/services/rent-website'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/web-design'
    | '/blog/'
    | '/industries/'
    | '/location/'
    | '/services/'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  GoogleAdsBriefRoute: typeof GoogleAdsBriefRoute
  GrowYourBusinessFormRoute: typeof GrowYourBusinessFormRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  LocationRoute: typeof LocationRouteWithChildren
  PayPerLeadForTradiesRoute: typeof PayPerLeadForTradiesRoute
  PayPerLeadServiceBriefRoute: typeof PayPerLeadServiceBriefRoute
  RentWebsiteBriefRoute: typeof RentWebsiteBriefRoute
  SeoBriefRoute: typeof SeoBriefRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialMediaBriefRoute: typeof SocialMediaBriefRoute
  ThankYouRoute: typeof ThankYouRoute
  WebDesignBriefRoute: typeof WebDesignBriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-design-brief': {
      id: '/web-design-brief'
      path: '/web-design-brief'
      fullPath: '/web-design-brief'
      preLoaderRoute: typeof WebDesignBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-brief': {
      id: '/social-media-brief'
      path: '/social-media-brief'
      fullPath: '/social-media-brief'
      preLoaderRoute: typeof SocialMediaBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-brief': {
      id: '/seo-brief'
      path: '/seo-brief'
      fullPath: '/seo-brief'
      preLoaderRoute: typeof SeoBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-website-brief': {
      id: '/rent-website-brief'
      path: '/rent-website-brief'
      fullPath: '/rent-website-brief'
      preLoaderRoute: typeof RentWebsiteBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-per-lead-service-brief': {
      id: '/pay-per-lead-service-brief'
      path: '/pay-per-lead-service-brief'
      fullPath: '/pay-per-lead-service-brief'
      preLoaderRoute: typeof PayPerLeadServiceBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-per-lead-for-tradies': {
      id: '/pay-per-lead-for-tradies'
      path: '/pay-per-lead-for-tradies'
      fullPath: '/pay-per-lead-for-tradies'
      preLoaderRoute: typeof PayPerLeadForTradiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow-your-business-form': {
      id: '/grow-your-business-form'
      path: '/grow-your-business-form'
      fullPath: '/grow-your-business-form'
      preLoaderRoute: typeof GrowYourBusinessFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads-brief': {
      id: '/google-ads-brief'
      path: '/google-ads-brief'
      fullPath: '/google-ads-brief'
      preLoaderRoute: typeof GoogleAdsBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/location/': {
      id: '/location/'
      path: '/'
      fullPath: '/location/'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof LocationRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/web-design': {
      id: '/services/web-design'
      path: '/web-design'
      fullPath: '/services/web-design'
      preLoaderRoute: typeof ServicesWebDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media-marketing': {
      id: '/services/social-media-marketing'
      path: '/social-media-marketing'
      fullPath: '/services/social-media-marketing'
      preLoaderRoute: typeof ServicesSocialMediaMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rent-website': {
      id: '/services/rent-website'
      path: '/rent-website'
      fullPath: '/services/rent-website'
      preLoaderRoute: typeof ServicesRentWebsiteRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/pay-per-lead': {
      id: '/services/pay-per-lead'
      path: '/pay-per-lead'
      fullPath: '/services/pay-per-lead'
      preLoaderRoute: typeof ServicesPayPerLeadRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/google-ads': {
      id: '/services/google-ads'
      path: '/google-ads'
      fullPath: '/services/google-ads'
      preLoaderRoute: typeof ServicesGoogleAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof LocationRoute
    }
    '/industries/digital-marketing-for-tradie': {
      id: '/industries/digital-marketing-for-tradie'
      path: '/digital-marketing-for-tradie'
      fullPath: '/industries/digital-marketing-for-tradie'
      preLoaderRoute: typeof IndustriesDigitalMarketingForTradieRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-small-businesses': {
      id: '/industries/digital-marketing-for-small-businesses'
      path: '/digital-marketing-for-small-businesses'
      fullPath: '/industries/digital-marketing-for-small-businesses'
      preLoaderRoute: typeof IndustriesDigitalMarketingForSmallBusinessesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-restaurant': {
      id: '/industries/digital-marketing-for-restaurant'
      path: '/digital-marketing-for-restaurant'
      fullPath: '/industries/digital-marketing-for-restaurant'
      preLoaderRoute: typeof IndustriesDigitalMarketingForRestaurantRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-real-estates': {
      id: '/industries/digital-marketing-for-real-estates'
      path: '/digital-marketing-for-real-estates'
      fullPath: '/industries/digital-marketing-for-real-estates'
      preLoaderRoute: typeof IndustriesDigitalMarketingForRealEstatesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-professional-services': {
      id: '/industries/digital-marketing-for-professional-services'
      path: '/digital-marketing-for-professional-services'
      fullPath: '/industries/digital-marketing-for-professional-services'
      preLoaderRoute: typeof IndustriesDigitalMarketingForProfessionalServicesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-non-profits': {
      id: '/industries/digital-marketing-for-non-profits'
      path: '/digital-marketing-for-non-profits'
      fullPath: '/industries/digital-marketing-for-non-profits'
      preLoaderRoute: typeof IndustriesDigitalMarketingForNonProfitsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-law-firms': {
      id: '/industries/digital-marketing-for-law-firms'
      path: '/digital-marketing-for-law-firms'
      fullPath: '/industries/digital-marketing-for-law-firms'
      preLoaderRoute: typeof IndustriesDigitalMarketingForLawFirmsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-fitness': {
      id: '/industries/digital-marketing-for-fitness'
      path: '/digital-marketing-for-fitness'
      fullPath: '/industries/digital-marketing-for-fitness'
      preLoaderRoute: typeof IndustriesDigitalMarketingForFitnessRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-financial-services': {
      id: '/industries/digital-marketing-for-financial-services'
      path: '/digital-marketing-for-financial-services'
      fullPath: '/industries/digital-marketing-for-financial-services'
      preLoaderRoute: typeof IndustriesDigitalMarketingForFinancialServicesRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-doctor': {
      id: '/industries/digital-marketing-for-doctor'
      path: '/digital-marketing-for-doctor'
      fullPath: '/industries/digital-marketing-for-doctor'
      preLoaderRoute: typeof IndustriesDigitalMarketingForDoctorRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-dentists': {
      id: '/industries/digital-marketing-for-dentists'
      path: '/digital-marketing-for-dentists'
      fullPath: '/industries/digital-marketing-for-dentists'
      preLoaderRoute: typeof IndustriesDigitalMarketingForDentistsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/digital-marketing-for-beauty-skincare': {
      id: '/industries/digital-marketing-for-beauty-skincare'
      path: '/digital-marketing-for-beauty-skincare'
      fullPath: '/industries/digital-marketing-for-beauty-skincare'
      preLoaderRoute: typeof IndustriesDigitalMarketingForBeautySkincareRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface IndustriesRouteChildren {
  IndustriesDigitalMarketingForBeautySkincareRoute: typeof IndustriesDigitalMarketingForBeautySkincareRoute
  IndustriesDigitalMarketingForDentistsRoute: typeof IndustriesDigitalMarketingForDentistsRoute
  IndustriesDigitalMarketingForDoctorRoute: typeof IndustriesDigitalMarketingForDoctorRoute
  IndustriesDigitalMarketingForFinancialServicesRoute: typeof IndustriesDigitalMarketingForFinancialServicesRoute
  IndustriesDigitalMarketingForFitnessRoute: typeof IndustriesDigitalMarketingForFitnessRoute
  IndustriesDigitalMarketingForLawFirmsRoute: typeof IndustriesDigitalMarketingForLawFirmsRoute
  IndustriesDigitalMarketingForNonProfitsRoute: typeof IndustriesDigitalMarketingForNonProfitsRoute
  IndustriesDigitalMarketingForProfessionalServicesRoute: typeof IndustriesDigitalMarketingForProfessionalServicesRoute
  IndustriesDigitalMarketingForRealEstatesRoute: typeof IndustriesDigitalMarketingForRealEstatesRoute
  IndustriesDigitalMarketingForRestaurantRoute: typeof IndustriesDigitalMarketingForRestaurantRoute
  IndustriesDigitalMarketingForSmallBusinessesRoute: typeof IndustriesDigitalMarketingForSmallBusinessesRoute
  IndustriesDigitalMarketingForTradieRoute: typeof IndustriesDigitalMarketingForTradieRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesDigitalMarketingForBeautySkincareRoute:
    IndustriesDigitalMarketingForBeautySkincareRoute,
  IndustriesDigitalMarketingForDentistsRoute:
    IndustriesDigitalMarketingForDentistsRoute,
  IndustriesDigitalMarketingForDoctorRoute:
    IndustriesDigitalMarketingForDoctorRoute,
  IndustriesDigitalMarketingForFinancialServicesRoute:
    IndustriesDigitalMarketingForFinancialServicesRoute,
  IndustriesDigitalMarketingForFitnessRoute:
    IndustriesDigitalMarketingForFitnessRoute,
  IndustriesDigitalMarketingForLawFirmsRoute:
    IndustriesDigitalMarketingForLawFirmsRoute,
  IndustriesDigitalMarketingForNonProfitsRoute:
    IndustriesDigitalMarketingForNonProfitsRoute,
  IndustriesDigitalMarketingForProfessionalServicesRoute:
    IndustriesDigitalMarketingForProfessionalServicesRoute,
  IndustriesDigitalMarketingForRealEstatesRoute:
    IndustriesDigitalMarketingForRealEstatesRoute,
  IndustriesDigitalMarketingForRestaurantRoute:
    IndustriesDigitalMarketingForRestaurantRoute,
  IndustriesDigitalMarketingForSmallBusinessesRoute:
    IndustriesDigitalMarketingForSmallBusinessesRoute,
  IndustriesDigitalMarketingForTradieRoute:
    IndustriesDigitalMarketingForTradieRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface LocationRouteChildren {
  LocationSlugRoute: typeof LocationSlugRoute
  LocationIndexRoute: typeof LocationIndexRoute
}

const LocationRouteChildren: LocationRouteChildren = {
  LocationSlugRoute: LocationSlugRoute,
  LocationIndexRoute: LocationIndexRoute,
}

const LocationRouteWithChildren = LocationRoute._addFileChildren(
  LocationRouteChildren,
)

interface ServicesRouteChildren {
  ServicesGoogleAdsRoute: typeof ServicesGoogleAdsRoute
  ServicesPayPerLeadRoute: typeof ServicesPayPerLeadRoute
  ServicesRentWebsiteRoute: typeof ServicesRentWebsiteRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialMediaMarketingRoute: typeof ServicesSocialMediaMarketingRoute
  ServicesWebDesignRoute: typeof ServicesWebDesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesGoogleAdsRoute: ServicesGoogleAdsRoute,
  ServicesPayPerLeadRoute: ServicesPayPerLeadRoute,
  ServicesRentWebsiteRoute: ServicesRentWebsiteRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialMediaMarketingRoute: ServicesSocialMediaMarketingRoute,
  ServicesWebDesignRoute: ServicesWebDesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  GoogleAdsBriefRoute: GoogleAdsBriefRoute,
  GrowYourBusinessFormRoute: GrowYourBusinessFormRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  LocationRoute: LocationRouteWithChildren,
  PayPerLeadForTradiesRoute: PayPerLeadForTradiesRoute,
  PayPerLeadServiceBriefRoute: PayPerLeadServiceBriefRoute,
  RentWebsiteBriefRoute: RentWebsiteBriefRoute,
  SeoBriefRoute: SeoBriefRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialMediaBriefRoute: SocialMediaBriefRoute,
  ThankYouRoute: ThankYouRoute,
  WebDesignBriefRoute: WebDesignBriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
